# Generated by Django 3.0.1 on 2019-12-25 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='comment_time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='dynamicinfo',
            name='dynamic_time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='dynamictopic',
            name='topic_create_time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='likes',
            name='likes_time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='news',
            name='news_time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='notice',
            name='notice_time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='place',
            name='submit_time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='replyquestion',
            name='reply_time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='resource',
            name='submit_time',
            field=models.DateTimeField(),
        ),
    ]
